version: "3.9"
services:
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - testnet
  api:
    container_name: api
    image: cinnox-homework
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - testnet
networks:
  testnet:
